import { CreditNoteDto, InvoiceDto, PurchaseOrderDto } from "./documentAdapter";

export const mockInvoice: InvoiceDto = {
  invoiceNumber: "FAC-2026-00009",
  issueDate: "2026-05-25",
  dueDate: "2026-06-09",
  currency: "TND",
  invoiceStatus: "TO_PAY",
  paymentTerms: "NET_15",
  paymentMethod: "BANK_TRANSFER",
  partner: null,
  items: [],
};

export const mockInvoiceWithClient: InvoiceDto = {
  invoiceNumber: "FAC-2026-00024",
  issueDate: "2026-05-25",
  dueDate: "2026-06-24",
  currency: "TND",
  invoiceStatus: "TO_PAY",
  paymentTerms: "NET_30",
  paymentMethod: "BANK_TRANSFER",
  partner: {
    firstName: "Ahmed",
    lastName: "Ben Salem",
    companyName: "Ben Salem Consulting",
    email: "ahmed.bensalem@example.com",
    workPhone: "+216 71 123 456",
    mobilePhone: "+216 98 765 432",
    taxId: "1234567/A/M/000",
    billingStreet1: "12 Rue de la liberté",
    billingStreet2: "Immeuble B, 2ème étage",
    billingCity: "Tunis",
    billingState: "Tunis",
    billingZip: "1002",
    billingCountry: "Tunisie",
  },
  items: [
    {
      description: "Développement module facturation",
      reference: "DEV-BILLING-001",
      category: "Prestation de Service",
      quantity: 1,
      unitPrice: 1200,
      taxRate: 19,
      discountRate: 0,
    },
    {
      description: "Intégration génération PDF",
      reference: "PDF-GEN-001",
      category: "Prestation de Service",
      quantity: 2,
      unitPrice: 350,
      taxRate: 19,
      discountRate: 5,
    },
  ],
  notes: "Merci de procéder au paiement avant la date d’échéance indiquée sur la facture.",
};

export const mockCreditNote: CreditNoteDto = {
  creditNoteNumber: "AV-2026-00008",
  originalInvoiceNumber: "FAC-2026-00024",
  issueDate: "2026-05-25",
  currency: "TND",
  status: "NOT_REFUNDED",
  partner: mockInvoiceWithClient.partner,
  items: [
    {
      description: "Correction prestation facturée en double",
      reference: "PDF-GEN-001",
      category: "Prestation de Service",
      quantity: 1,
      unitPrice: 350,
      taxRate: 19,
      discountRate: 0,
    },
  ],
  notes: "Avoir émis suite à une correction de facturation liée à la facture originale.",
};

export const mockPurchaseOrder: PurchaseOrderDto = {
  purchaseOrderNumber: "BC-2026-00012",
  issueDate: "2026-05-25",
  deliveryDate: "2026-06-05",
  currency: "TND",
  purchaseOrderStatus: "DRAFT",
  supplier: {
    firstName: "Sarra",
    lastName: "Mansouri",
    companyName: "Tech Supply Tunisia",
    email: "contact@techsupply.tn",
    workPhone: "+216 70 555 888",
    mobilePhone: "+216 22 333 444",
    taxId: "7654321/B/M/000",
    billingStreet1: "45 Avenue Habib Bourguiba",
    billingStreet2: "Bloc C",
    billingCity: "Ariana",
    billingState: "Ariana",
    billingZip: "2080",
    billingCountry: "Tunisie",
  },
  items: [
    {
      description: "Ordinateur portable professionnel",
      reference: "LAPTOP-PRO-15",
      category: "Matériel informatique",
      quantity: 3,
      unitPrice: 2450,
      taxRate: 19,
      discountRate: 3,
    },
    {
      description: "Station d’accueil USB-C",
      reference: "DOCK-USBC-001",
      category: "Accessoire informatique",
      quantity: 3,
      unitPrice: 320,
      taxRate: 19,
      discountRate: 0,
    },
        {
      description: "Station d’accueil USB-C",
      reference: "DOCK-USBC-001",
      category: "Accessoire informatique",
      quantity: 3,
      unitPrice: 320,
      taxRate: 19,
      discountRate: 0,
    },
        {
      description: "Station d’accueil USB-C",
      reference: "DOCK-USBC-001",
      category: "Accessoire informatique",
      quantity: 3,
      unitPrice: 320,
      taxRate: 19,
      discountRate: 0,
    },
  ],
  notes: "Merci de confirmer la disponibilité des articles avant validation définitive du bon de commande.",
};
